### ISSUE TITLE
Installing jaratoolbox

### ISSUE THREAD

**Issue by sjara** [sjara/jaraviewer#1]
I created this issue to discuss any problems people may have installing [jaratoolbox](https://github.com/sjara/jaratoolbox). This way, everyone gets to see problems and solutions (instead of one-on-one emails).

**Comment by kyle-sammons** [comment]
Just a note to everyone else: When setting up the settings.py file for jaratoolbox, you have to use a full path for the data location (e.g. you can't use "~/data", you have to use "/home/username/data").

**Comment by sjara** [comment]
I'm closing this issue, as it looks like everyone successfully run jaratoolbox. Any other questions regarding jaratoolbox should be discussed on our Slack channel.
