### ISSUE TITLE
The meaning of "number of columns"

### ISSUE THREAD

**Issue by sjara** [sjara/jaraviewer#12]
I think there is some confusion about what "number of columns" should mean.
Plots for the same day, same animal should always be aligned horizontally. So, for example, if we make three plots for adap021 on 2016-03-10, those count as just ONE item (one column).

**Comment by honglux** [comment]
So, basically, you mean that we should put three "items" in one line if the user chooses 3 for the column number? That is 9 plots in one line if the users chooses 3 plot types.

OR

We just remove the "number of columns" function and let it fill the layout automatically?

**Comment by sjara** [comment]
Correct, if the user chooses 3 columns and 2 plot types, each row will have 6 plots. And remember that two plot types for the same animal same day should always be next to each other horizontally.

The "number of columns" parameter should also have the option of not specifying anything and letting the layout fill automatically.

**Comment by honglux** [comment]
OK, I think we got it, but since the size of the plot will not change depend on the number of plots, we will get kind of mass for the layout, like, 3 plot types and 5 columns will result to 15 large plots in one line. Will that be OK?

**Comment by sjara** [comment]
But the plots should not be too large. Choose a size that seems appropriate to you and I'll tell you if we need to change it.
Also, when the user doesn't specify the number of columns, the plots per columns will change when the user resizes the window, right?

**Comment by honglux** [comment]
Are we really need to do the case that the user didn't specify the column number, and then number of columns per row will change while re-sizing the window?

OR

We just force the user to choose a column number before submit?

**Comment by sjara** [comment]
The first option you wrote. I think it's important to have the "undefined number of columns" option as a way to maximize space available on the screen.
The "undefined" option should be the default on the front-end, talk to @nicolehsieh about this.
