### ISSUE TITLE
The size of plots should not change depending on how many plots we have

### ISSUE THREAD

**Issue by sjara** [sjara/jaraviewer#13]
Currently, the results page has a fixed width and the size of plots seems to change depending on how many plots we generate.
This should be changed so that plots always have the same size.

**Comment by honglux** [comment]
OK, that should be clear, just want to check, what is the size of the plots you except?
To be convenient to describe, what percentage of one plot's height compared to the full sized browser. And, what percentage of one plot's width compared to the full sized browser? Or, the width and height should be equal?
The real percentage of the plot will depend on the size of the screen and other things. Just give the estimated values so we can have some ideas about it.

**Comment by xiaoli999999** [comment]
Hi, professor. I made some screen cut about the new html, Could you check these out and give me some comment?
![1-2col](https://cloud.githubusercontent.com/assets/13024400/15414269/ecbff376-1ded-11e6-84a5-e8411e08ed24.png)
![2-3-col](https://cloud.githubusercontent.com/assets/13024400/15414272/f17f1c66-1ded-11e6-8efe-ae06d48c4942.png)
![4-col](https://cloud.githubusercontent.com/assets/13024400/15414273/f4f7d04a-1ded-11e6-847f-2b92974b9cf1.png)

**Comment by sjara** [comment]
@xiaoli999999 I'm not sure I understand. The one with 4 columns only has 3 columns.
The idea is that if it's 4 columns, the plots may be outside the view and the user has to use the horizontal scrollbar to see them.
If we need to have a longer discussion, let's do it on Slack.

**Comment by sjara** [comment]
@honglux Choose a size that seems appropriate to you and I'll tell you if we need to change it.
The idea is that all labels and data points should be readable, but the plots should be as compact as possible.
When the user resizes the window, the plots should not change size (but may change location). The user can always use Zoom-in/out from the browser to make them larger/smaller.

**Comment by xiaoli999999** [comment]
@sjara 
Made a new version, do you accept this style?
![new_version](https://cloud.githubusercontent.com/assets/13024400/15415860/92a565d0-1dfa-11e6-8eae-0680011fca3d.png)

**Comment by Jvargasw** [comment]
From meeting: Window size should not alter the size of the plots.
