### ISSUE TITLE
What is sent in the email generated by the alarm?

### ISSUE THREAD

**Issue by sjara** [sjara/jaraviewer#14]
What information will be sent by the alarm? Is all this information condensed in one email per user or will one user receive multiple emails?
What are the advantages and disadvantages of each approach?

**Comment by kyle-sammons** [comment]
Currently all that is sent is something along the lines of, "Subject: Alarm, Body: No data found for animal <animal name>/<animal name>'s average is below/above threshold". For each issue found, another email will be sent (at least in the alarms current form). I'm not sure on the advantages or disadvantages of each approach -- I suppose it largely comes down to personal opinion.

**Comment by sjara** [comment]
Think about what would happen for different approaches, and give me options.
The personal opinion is used to make the decision, but there are still objective advantages and disadvantages (and some other things that may or may not happen and we need to decide if they are an advantages or a disadvantages).

**Comment by sjara** [comment]
Also, recommend one option according to your personal opinion (as a user, not as a developer).

**Comment by kyle-sammons** [comment]
If we went the approach of one email per alert (e.g. person A would get an email if adap022 performed worse than expected, and they'd get an email if adap023 performed better than expected), then it could clutter someone's mail if there are many alerts. However, if we just condensed it all into one email, then it'd be easier to overlook a single alert, as it may just get lost in the fray. So personally, if I were running a lab where I'd want have someone check on each alert sent out, I'd have an email per alert, as it's harder to overlook them. Plus it'd be much easier to autofile said alerts into specific folders in an email box when you have one email per alert.

**Comment by sjara** [comment]
I agree that autofiling would be easier if we have separate emails, but I'm not sure one would want to autofile by subject/alarmType. Wouldn't that require the user to check many folders?

I agree that many individual emails would clutter the inbox.

I didn't understand the part about "_if we just condensed it all into one email, then it'd be easier to overlook a single alert_". If it's a single alert it will be one email anyway (equally likely to be lost). If it's multiple emails, there's probably a higher chance of missing one of them as opposed to finding the expected "daily" email that gives you a summary of everything.

It looks like to achieve what you say "_I'd want have someone check on each alert sent out_", one would either:
- Check all the alerts on the one summary email (single-email version)
- Tell the email client to search for all alerts on a particular day and check each one (multiple-email version). 

Is my interpretation consistent with what you are saying?

**Comment by kyle-sammons** [comment]
What I meant by, "if we just condensed it all into one email, then it'd be easier to overlook a single alert" is having to physically check, read, and delete each alert sent out seems like it'd force whoever's checking the alarms to at least acknowledge each one. Whereas if it was all in one email, I'd assume it'd be easier to ignore or overlook one of the alerts. Although I'm not a psychologist or neuroscientist by any means, so that may be completely incorrect.

**Comment by sjara** [comment]
Thanks for clarifying, that makes sense.
Although my preference is still a single email per user (after considering the issues discussed above), we're running out of time, so you can choose either implementation as long as it's appropriately documented.

**Comment by kyle-sammons** [comment]
I'll try to add in a single email per user if I have spare time this week, but for now I'll keep it how it is. I've documented this decision in the Alarm section of the Wiki.
