### ISSUE TITLE
If a plot exists, do not create it again

### ISSUE THREAD

**Issue by sjara** [sjara/jaraviewer#19]
To make the system more efficient, we should make sure that if a plot exists already we don't create it again (this is probably what takes the longest) but simply use the existing file.

**Comment by Jvargasw** [comment]
From our discussions in meetings, it sounded like to me that this was originally intended to be implemented into the backend as they were creating the list of dictionaries for me to use (since I get the filenames from the backend anyways).

**Comment by honglux** [comment]
So, the current version, on last meeting, has already finished the function for checking the existed plots. "check_exsit()" in "back_end_extend.py" will do this. I will make the comments for all the back_end files later for easier reading.

Also, for clarify, the systems will only read one piece of data once and do the plot function to generate the plot for now in case of memory overflow, said by @sjara. The output should be a dictionary only contains the data for one mouse and one date and one plot type. Not a list of them.

**Comment by sjara** [comment]
It sounds like @honglux already implemented what this issue describes. If so, please close this issue.

**Comment by honglux** [comment]
I will keep this for a while just to make sure the "Also, for clarify......" part is shown.
