### ISSUE TITLE
Add/Delete Subject

### ISSUE THREAD

**Issue by nicolehsieh** [sjara/jaraviewer#21]
I added a modify subject 1 and 2. (each has a input field, add/delete button) inside the original form.

And just in case that doesn't work, I added a 2nd form below the original. And the action is action=""  in index.html because I don't know what you will call that function in backend.py

Please let me know how it goes and if they both cannot be reached by backend.

**Comment by nicolehsieh** [comment]
Did any of the format above work?

**Comment by honglux** [comment]
The second method is ready to go, not sure how to apply the first one.
