### ISSUE TITLE
Methods for storing data

### ISSUE THREAD

**Issue by honglux** [sjara/jaraviewer#22]
Is it confirmed that we need to read the data one by one to prevent the memory overflow?
For the current version, the system will read one piece of data every time and pass it to the plotting module. 

Another way is:

Read all the data we need and store it in a list, then pass the list to the plotting module.

Which one should be the best way?

**Comment by sjara** [comment]
You should do some tests and see how much memory is needed.
Remember that it will be common to load 20 datasets at once.

We should also keep in mind the possibility of having the system generate the figures automatically (before the user requests them), as discussed in the meeting.

**Comment by Jvargasw** [comment]
From meeting: Make a version of plotgenerator that does only one plot at a time. Test the two against each other for memory usage

**Comment by honglux** [comment]
Test result:
1. Looping for storing all the data in one time and generate the plots with the list of dictionary.
    300 pieces of data, 316 images generated for: 2 minutes and 20 seconds
2. One piece of data each time, and one plot for each loop.
    300 pieces of data, 316 images generated for: 2 minutes and 23 seconds.

Note that the memory usage seems not be a problem in these cases.

**Comment by sjara** [comment]
Since they both take about the same amount of time, let's generate one plot
at a time.
To say that memory usage is not a problem we would need to know how much
memory is required (and how much we have in our server, some of which could
be in use), but I don't think we have the need to load them all at once
anyway, so just in case, it's safer one at a time.

**Comment by Jvargasw** [comment]
Closing; Resolved with decision to load a single plot at a time. Code changed for plotgenerator on 6/2
