### ISSUE TITLE
How should we treat profiles?

### ISSUE THREAD

**Issue by Jvargasw** [sjara/jaraviewer#28]
Should users be able to create their own profiles and have them stored server side (so that everyone else can see all the saved profiles)? Or, should the profiles be saved locally and give the ability to import profiles from another file?

**Comment by nicolehsieh** [comment]
User are able to create their own profiles and store the profile on the server side and everyone can see all the saved profiles. 

Pros:
Everyone can see your profile and easily access it. 

Cons:
Someone might be able to accidentally delete your profile

**Comment by honglux** [comment]
@nicolehsieh 
Yes, that is the current version.
