### ISSUE TITLE
Interface modes: simple and advanced

### ISSUE THREAD

**Issue by sjara** [sjara/jaraviewer#3]
On 2016-04-19 we discussed the possibility of having two modes/tabs for the web interface: a simple one (single animal/date) and an advanced one (multiple animals, date ranges).

In the lab, we rarely need to run a single animal during a single date, so I think the simple interface may not be very useful. Let's start working on the full interface, and we can discuss later what the most common searches are (from which we could create a "simple" mode in the future).

**Comment by nicolehsieh** [comment]
Got it. Thanks for the clarifications.
