### ISSUE TITLE
Installation Wiki - HELP!!!

### ISSUE THREAD

**Issue by nicolehsieh** [sjara/jaraviewer#42]
Can someone please go through what I wrote in meeting today AND
- verify if it's correct, or
- modify what need to be change, or
- add more details to where you think it is unclear

I will follow those instruction and install it on my computer when James and I do testing later this week.

**Comment by nicolehsieh** [comment]
Please add instruction for jaratoolbox installation and dependencies to be install.

**Comment by nicolehsieh** [comment]
This is the error message that I see on terminal when I try to run `$  python jaraviewerapp.py`

```
$ python jaraviewerapp.py 
Traceback (most recent call last):
  File "jaraviewerapp.py", line 12, in <module>
    from jaraviewer import backend
ImportError: No module named jaraviewer

```

This is without installing jaratoolbox and only pip install numpy

**Comment by sjara** [comment]
The folder where jaraviewer resides needs to be in the Python path.
