### ISSUE TITLE
Data for the plot.

### ISSUE THREAD

**Issue by honglux** [sjara/jaraviewer#5]
So here's the questions for the data arrangement and transmission for both back_end and plot generation module. I hope we can figure that out together.
1. How many types of plots do we need, and what are they?
2. What is the required input data for each plot type?
3. What is the format for data transmission between the back_end and plot generation module?

**Comment by nicolehsieh** [comment]
There are three types of plots; psychometric, performance summary, and performance dynamic.

**Comment by sjara** [comment]
1. As @nicolehsieh said, we will have three types. The short names that we can use for each are "psychometric", "summary" and "dynamics".
2. That's for the back-end group to figure out. The plotting functions in jaratoolbox will have that information. For example, check how behavioranalysis.plot_frequency_psycurve() takes the raw data and calls the method extraplots.plot_psychometric() to generate the plot.
3. The back-end module should generate these data as numpy arrays. The plotting module will convert the data to whatever format it needs. The plotting module should not do any analysis, just plot.

**Comment by Jvargasw** [comment]
As a sort of additional question to this, I'm assuming the graphing module will be receiving more than just a numpy array? I figured the input would be something like (graphTypes, graphData) where graphTypes is an array of strings determining, in order, what graphs have been requested while the graphData is either a single or multiple numpy arrays containing all of the data for the requested plots

**Comment by sjara** [comment]
One idea is that what the plotting module receives is a list of dictionaries, such as:
`plotList = [plotDict1, plotDict2, plotDict3]`
where each dictionary looks something like:
`plotDict1 = {'type':'psychometric', 'title':'My plot', 'xdata':[0,1,2], 'ydata':[0.4,0.1,2.2]}`

**Comment by Jvargasw** [comment]
That is perfect.
